### ISSUE TITLE
Service will break for timed blue/green deployment by kubernetes

### ISSUE THREAD

**Issue by wangyoucao577** [Telenav/osrm-backend#25]
By the draft design [OSRM with Telenav Traffic Design (Draft)](https://github.com/Telenav/osrm-backend/blob/master-telenav/docs/design/osrm-with-telenav-traffic.md), we hope to use timed blue/green deploy by Kubernetes to support live traffic update without any service breakup.
In the test there're several issues occurred: 
1. The startup process(`pull latest traffic and dump to traffic.csv file`, `osrm-customize`, `osrm-routed`) totally need about more than 15 minutes for North America. 
    - It's not critical but too much time to let the live traffic effective. We have to figure out better way to shorten it. 
2. The `blue/green` deploy will terminate old container once new container running. But it needs about 15 minutes from the new container running to the new container service ready as above, the service will be unavailable in this 15 minutes. 
    - It will be good if kubernetes have some settings to switch service to new container until new container service ready, e.g. something like heartbeat check. Not sure whether kubernetes have such setting, need to do some research.

**Comment by wangyoucao577** [comment]
The `kubernetes readiness probe` looks for this requirement. See details in: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
Will have a try.

**Comment by wangyoucao577** [comment]
It works well. The `POD` will be set to ready until the probe succeed.
```
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 1000
```
